### ISSUE TITLE
The packaged wheel doesn't provide bill_calculator_hep

### ISSUE THREAD

**Issue by jcpunk** [HEPCloud/bill-calculator-hep#1]
It is providing a `lib` module rather than the `bill_calculator_hep` namespace.

**Comment by mapsacosta** [comment]
Thanks @jcpunk ! I just restored previous build behavior, can you please try with v0.1.0?

```pip install bill-calculator-hep==0.1.0```

**Comment by jcpunk** [comment]
Version 0.1.0 does look to have the right layout.  The proposed PR is an attempt to make this code layout match the other hepcloud default layouts.

**Comment by jcpunk** [comment]
Is version 0.1.0 up on pypi the version we should be using in production?

**Comment by mapsacosta** [comment]
@jcpunk yes, 0.1.0 is the production version and we will mark upgrades with 0.1.0 as base. Checking and testing #2

**Comment by mapsacosta** [comment]
bill-calculator-hep 0.1.1 with changes from #2 has been released: https://pypi.org/project/bill-calculator-hep/
