### ISSUE TITLE
Inconsistency in name of package and top level directory / module name.

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/bill-calculator-hep#4]
With the port of the bill-calculator-hep to the hepcloud git repo, it has changed
names in a confusing way.

The pip3 package as stored in pypi is called bill-calculator-hep
The dist-info directory is bill_calculator_hep-0.1.2.dist-info
But the actual source directory that's untarred is billing_calculator_hep.

Everything works, the code is functional, but it seems a big inconsistency to have the dist-info directory and the package name, not match the top level dir of the package.

**Comment by mapsacosta** [comment]
All the changes to fix this are done ( see 35a4601) @StevenCTimm can you please verify that v0.1.4 works for you and feed that back on this same issue? I'd like to wait for confirmation before closing in case there's something else that needs to be done.


https://pypi.org/project/bill-calculator-hep/

CC @mambelli @jcpunk

**Comment by mapsacosta** [comment]
I got verbal confirmation from @StevenCTimm that this Issue has been solved. Closing now.
